<a href="https://colab.research.google.com/github/KrolDaniel-DTEU/ML-FIT-3-16/blob/main/%D0%9A%D1%80%D0%BE%D0%BB%D1%8C_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Варіант 8
# Кроль 3-16

import numpy as np

In [ ]:
# Завдання 1

# Створіть одновимірний масив (вектор) зі спадаючою послідовністю чисел, де кожне
# наступне число менше попереднього на 2, починаючи з 30, та виведіть його значення.

arr = np.arange(30, 0, -2)
print(arr)

[30 28 26 24 22 20 18 16 14 12 10  8  6  4  2]


In [ ]:
# Завдання 2

# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
# факторіалів натуральних чисел, починаючи з 1, та виведіть його значення.

numbers = np.arange(1, 10)
factorials = np.cumprod(numbers)
matrix = factorials.reshape(3, 3)

print(matrix)


[[     1      2      6]
 [    24    120    720]
 [  5040  40320 362880]]


In [ ]:
# Завдання 3

# Створіть масив розміром 4x4, заповніть його випадковими цілими числами
# від 1 до 10 та виведіть його значення

matrix = np.random.randint(1, 11, (4, 4))

print(matrix)

[[10  8  6  4]
 [ 5  2  5  2]
 [ 2  8  8  6]
 [ 6  6  2  9]]


In [ ]:
# Завдання 4

# Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та обчисліть суму всіх діагональних елементів

matrix = np.random.uniform(0, 1, (6, 6))
diagonal = np.diag(matrix)
sd = np.sum(diagonal)
print(f"{matrix=}")
print(f"{diagonal=}")
print(f"{sd=}")

matrix=array([[0.35108296, 0.42829846, 0.30242925, 0.85239313, 0.85187717,
        0.12014364],
       [0.45340224, 0.71843042, 0.08141516, 0.07211393, 0.89072011,
        0.69714628],
       [0.4580584 , 0.21085316, 0.27548343, 0.82451887, 0.46317177,
        0.81778795],
       [0.8201691 , 0.93171306, 0.46629965, 0.96617857, 0.91223008,
        0.71036668],
       [0.37784907, 0.59376627, 0.20495827, 0.34241368, 0.32911688,
        0.40363045],
       [0.70947839, 0.00923959, 0.01871877, 0.9486603 , 0.06892919,
        0.15997122]])
diagonal=array([0.35108296, 0.71843042, 0.27548343, 0.96617857, 0.32911688,
       0.15997122])
sd=np.float64(2.800263475454294)


In [ ]:
# Завдання 5

# Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними
# числами від -10 до 10 та виконайте на них поелементні операції додавання,
# віднімання та множення

arr1 = np.random.uniform(-10, 10, 4)
arr2 = np.random.uniform(-10, 10, 4)

print(f"{arr1=}")
print(f"{arr2=}")
print(f"{arr1 + arr2=}")
print(f"{arr1 - arr2=}")
print(f"{arr1 * arr2=}")

arr1=array([-1.56255093,  1.25776802,  4.52033158, -5.11051848])
arr2=array([ 2.69757449,  6.81164799, -1.06964486,  0.579967  ])
arr1 + arr2=array([ 1.13502357,  8.06941601,  3.45068673, -4.53055148])
arr1 - arr2=array([-4.26012542, -5.55387997,  5.58997644, -5.69048548])
arr1 * arr2=array([-4.21509752,  8.567473  , -4.83514942, -2.96393207])


In [ ]:
# Завдання 6

# Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 5 та
# знайдіть їх добуток

m1 = np.random.randint(1, 6, (4, 4))
m2 = np.random.randint(1, 6, (4, 4))

prod = np.dot(m1, m2)

print(f"{m1=}")
print(f"{m2=}")
print(f"{prod=}")

m1=array([[2, 5, 1, 4],
       [1, 2, 2, 5],
       [1, 4, 4, 4],
       [1, 1, 2, 3]])
m2=array([[2, 3, 1, 5],
       [2, 4, 2, 4],
       [1, 5, 4, 3],
       [2, 5, 5, 3]])
prod=array([[23, 51, 36, 45],
       [18, 46, 38, 34],
       [22, 59, 45, 45],
       [12, 32, 26, 24]])


In [ ]:
# Завдання 7

# Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими
# цілими числами в діапазоні від 1 до 4 та перемножте їх між собою

m1 = np.random.randint(1, 5, (2, 3))
m2 = np.random.randint(1, 5, (3, 3))

prod = np.dot(m1, m2)

print(f"{m1=}")
print(f"{m2=}")
print(f"{prod=}")

m1=array([[3, 1, 2],
       [2, 2, 1]])
m2=array([[4, 3, 4],
       [3, 2, 3],
       [1, 3, 1]])
prod=array([[17, 17, 17],
       [15, 13, 15]])


In [ ]:
# Завдання 8

# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в
# діапазоні від 1 до 7 та знайдіть її обернену матрицю

matrix = np.random.randint(1, 8, (3, 3))
invert = np.linalg.inv(matrix)

print(f"{matrix=}")
print(f"{invert=}")


matrix=array([[1, 2, 1],
       [2, 3, 7],
       [4, 5, 4]])
invert=array([[-1.53333333, -0.2       ,  0.73333333],
       [ 1.33333333,  0.        , -0.33333333],
       [-0.13333333,  0.2       , -0.06666667]])


In [ ]:
# Завдання 9

# Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
# діапазоні від -5 до 5 та транспонуйте її

matrix = np.random.uniform(-5, 5, (5, 5))
trans = matrix.transpose();

print(f"{matrix=}")
print(f"{trans=}")


matrix=array([[-3.77719665, -4.04158789,  1.68126023, -4.85145302,  4.39690385],
       [-3.85402499,  4.05516141,  4.86910358, -0.35498921,  1.39543042],
       [ 0.19156345, -4.69500573, -3.32666014,  4.61112034, -3.38399612],
       [ 3.18077191,  0.20654696, -4.7369738 ,  4.22091972,  0.24535249],
       [ 2.11953981, -0.61503211, -2.25835092,  0.95407914,  0.90203553]])
trans=array([[-3.77719665, -3.85402499,  0.19156345,  3.18077191,  2.11953981],
       [-4.04158789,  4.05516141, -4.69500573,  0.20654696, -0.61503211],
       [ 1.68126023,  4.86910358, -3.32666014, -4.7369738 , -2.25835092],
       [-4.85145302, -0.35498921,  4.61112034,  4.22091972,  0.95407914],
       [ 4.39690385,  1.39543042, -3.38399612,  0.24535249,  0.90203553]])


In [ ]:
# Завдання 10

# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
# випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
# числами від 0 до 1 і знайдіть добуток матриці на вектор

matrix = np.random.randint(1, 11, (3, 4))
arr = np.random.uniform(0, 1, 4)
prod = np.dot(matrix, arr)

print(f"{matrix=}")
print(f"{arr=}")
print(f"{prod=}")


matrix=array([[ 7, 10,  1,  7],
       [ 1,  5,  9,  7],
       [ 3,  4,  9,  4]])
arr=array([0.64244913, 0.91768056, 0.91550495, 0.50872143])
prod=array([18.15050448, 17.03144647, 15.87249987])


In [ ]:
# Завдання 11

# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
# випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
# від 0 до 1, і знайдіть добуток матриці на вектор

matrix = np.random.uniform(0, 1, (2, 3))
arr = np.random.uniform(0, 1, 3)
prod = np.dot(matrix, arr)

print(f"{matrix=}")
print(f"{arr=}")
print(f"{prod=}")

matrix=array([[0.54478613, 0.80445864, 0.00505636],
       [0.34052071, 0.25725111, 0.05924261]])
arr=array([0.87711853, 0.26708326, 0.82815325])
prod=array([0.69688689, 0.41644646])


In [ ]:
# Завдання 12

# Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 10 та знайдіть відношення елементів другої матриці до першої
# (поелементне ділення)

m1 = np.random.randint(1, 11, (9, 9))
m2 = np.random.randint(1, 11, (9, 9))

print(f"{m1=}")
print(f"{m2=}")
print(f"{m1/m2=}")

m1=array([[ 5,  5,  5,  4,  4,  5,  4,  1,  8],
       [ 3,  8,  4,  8,  7, 10,  4,  4,  1],
       [ 2,  2,  7,  1,  7,  2,  7,  1,  5],
       [ 2,  8,  9, 10,  9,  5,  4, 10,  3],
       [ 2,  9,  9,  7,  7,  5,  5,  9, 10],
       [ 8,  3,  4,  4,  7,  7,  4,  3,  7],
       [ 3,  8,  2,  5,  1,  5,  4,  4,  3],
       [ 2,  4, 10,  9,  6,  4,  4,  8,  1],
       [ 1,  3,  5,  1,  4,  4,  8, 10,  5]])
m2=array([[ 8,  8,  7,  9,  6,  8,  2, 10,  8],
       [ 2,  1,  1,  6,  2,  7, 10,  9,  6],
       [ 3,  4,  5,  2,  6,  2,  1,  9,  2],
       [ 1, 10,  2,  1,  5,  7,  4,  3, 10],
       [ 8,  6,  5,  5,  1,  4,  9, 10,  6],
       [10,  9,  4,  1,  8,  6, 10,  5,  7],
       [ 6,  6,  4,  4,  7,  2,  1,  9,  5],
       [ 4, 10,  3,  4,  3,  3,  8,  5,  1],
       [ 6, 10,  7,  4,  3,  7,  8,  7,  5]])
m1/m2=array([[ 0.625     ,  0.625     ,  0.71428571,  0.44444444,  0.66666667,
         0.625     ,  2.        ,  0.1       ,  1.        ],
       [ 1.5       ,  8.        ,  4.     

In [ ]:
# Завдання 13

# Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 5 та знайдіть їх добуток

m1 = np.random.randint(1, 6, (9, 9))
m2 = np.random.randint(1, 6, (9, 9))
prod = np.dot(m1, m2)

print(f"{m1=}")
print(f"{m2=}")
print(f"{prod=}")

m1=array([[4, 4, 2, 3, 4, 2, 4, 1, 2],
       [4, 3, 4, 1, 2, 2, 5, 3, 1],
       [2, 4, 4, 1, 4, 1, 5, 4, 2],
       [3, 5, 4, 1, 5, 2, 5, 3, 5],
       [3, 2, 1, 5, 1, 5, 3, 3, 3],
       [4, 2, 1, 2, 1, 2, 3, 2, 1],
       [1, 5, 3, 4, 2, 5, 1, 5, 2],
       [4, 5, 4, 2, 2, 4, 2, 3, 5],
       [2, 4, 5, 3, 1, 5, 5, 5, 4]])
m2=array([[3, 2, 2, 5, 4, 1, 5, 5, 4],
       [3, 3, 5, 3, 4, 2, 2, 1, 1],
       [2, 2, 5, 4, 5, 2, 3, 2, 1],
       [2, 1, 1, 4, 5, 2, 4, 4, 4],
       [5, 5, 3, 2, 1, 4, 5, 4, 1],
       [5, 4, 3, 2, 1, 5, 3, 4, 1],
       [4, 4, 4, 3, 3, 5, 1, 4, 4],
       [2, 5, 2, 2, 5, 1, 5, 4, 1],
       [5, 2, 5, 1, 2, 3, 4, 4, 4]])
prod=array([[ 92,  80,  87,  80,  84,  75,  89,  92,  65],
       [ 82,  81,  87,  79,  89,  69,  82,  87,  58],
       [ 91,  93,  98,  77,  93,  76,  90,  90,  57],
       [120, 108, 124,  90, 104,  96, 112, 112,  75],
       [ 90,  77,  77,  75,  86,  75,  92,  99,  68],
       [ 60,  55,  55,  58,  63,  48,  63,  68,  48],
       [ 91,  9

In [ ]:
# Завдання 14

# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
# від -5 до 5 та знайдіть середнє арифметичне значення елементів матриці.

matrix = np.random.uniform(-5, 5, (3, 3))
mean = np.mean(matrix)

print(f"{matrix=}")
print(f"{mean=}")

matrix=array([[-3.46927082,  1.29212311, -0.2735641 ],
       [-1.05584523,  3.68827556, -3.73900456],
       [ 0.35152379,  1.23113769,  4.9663807 ]])
mean=np.float64(0.3324173506835336)


In [ ]:
# Завдання 15

# Створіть матрицю розміром 10x10, заповніть її випадковими дійсними числами в
# діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем
# значення елементу у кожному рядку матриці.

matrix = np.random.uniform(-2, 2, (10, 10))
min_indices = np.argmin(np.abs(matrix), axis=1)
min_elements = matrix[np.arange(matrix.shape[0]), min_indices]
min_column_vector = min_elements.reshape(-1, 1)

print(f"{matrix=}")
print(f"{min_column_vector=}")

matrix=array([[-0.44194263,  0.44660665,  1.32787445, -1.42416695,  0.53001556,
        -0.48484046, -0.58949326, -1.79111817,  1.41773959,  0.68454377],
       [ 1.17461914, -1.687385  , -0.73574826, -1.05643851,  1.2493935 ,
         1.14087138, -1.31541272,  1.52240052, -0.64075899, -1.07085369],
       [ 0.96340356,  0.66099581,  0.32947176,  1.32372634, -1.19802689,
        -0.33289523, -1.59536541, -1.88065837, -0.95834115,  1.22871341],
       [ 0.91262712,  1.55227349,  1.97536836, -0.16303554, -0.36979797,
         1.16339488, -1.14701999,  0.91406046, -0.61182544, -1.53304   ],
       [-0.36675056, -1.8695876 , -0.5210177 , -0.61803842,  0.73447023,
        -1.16235398, -1.28669307, -0.01129167,  0.0148686 , -0.25989714],
       [ 1.54675051, -1.50145405,  1.77402978, -0.06197559,  1.78364181,
         1.76231994, -1.21254839, -0.12912207,  1.8941006 ,  1.23286715],
       [-1.81560199, -1.39306192,  1.09059855,  1.95665492,  1.22129025,
        -1.22566186, -0.73697881,  1.3

In [ ]:
# Висновок
# Отримано навички роботи з numpy, роботи з массивами та векторами а також порядок проводження дій над ними.